# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-06 12:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('nombre_a', models.CharField(max_length=128, verbose_name='Nombre del Alumno')),
                ('apellido_a', models.CharField(max_length=128, verbose_name='Apellido del Alumno')),
                ('dni', models.IntegerField(primary_key=True, serialize=False, verbose_name='Clave de Alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('materia_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Clave de materia')),
                ('nombre_m', models.CharField(max_length=128, verbose_name='Nombre de la materia')),
            ],
        ),
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField(verbose_name='Valor de la nota')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('nombre_p', models.CharField(max_length=128, verbose_name='Nombre del Profesor')),
                ('apellido_p', models.CharField(max_length=128, verbose_name='Apellido del Profesor')),
                ('dni', models.IntegerField(primary_key=True, serialize=False, verbose_name='Clave de profesor')),
                ('materia_p', models.ManyToManyField(to='app.Materia')),
            ],
        ),
        migrations.AddField(
            model_name='alumno',
            name='materia_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Materia'),
        ),
    ]
