# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-10 01:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180406_1254'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='materia_a',
        ),
        migrations.AddField(
            model_name='notas',
            name='materia',
            field=models.ForeignKey(default=213, on_delete=django.db.models.deletion.CASCADE, to='app.Materia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matricula',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Alumno'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Materia'),
        ),
    ]
