# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-10 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180410_0116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesor',
            name='materia_p',
        ),
        migrations.AddField(
            model_name='materia',
            name='profesor',
            field=models.ForeignKey(default=32, on_delete=django.db.models.deletion.CASCADE, to='app.Profesor'),
            preserve_default=False,
        ),
    ]
