# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-10 14:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180410_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notas',
            name='materia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Materia'),
        ),
    ]
